// <auto-generated />
using System;
using System.Collections.Generic;
using AlmacenApi.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlmacenApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260401165259_UpdateComboOutEntity")]
    partial class UpdateComboOutEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Admin.AdminEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwordHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.CombOut.ComboOutEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComboId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<string>("OutMotive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateComboid")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ComboId");

                    b.HasIndex("UpdateComboid");

                    b.HasIndex("UserId");

                    b.ToTable("ComboOut");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Combo.ComboEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("AdminId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Combo");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Out.ProductOut.ProductOutEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("AdminId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutMotive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductOut");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("ComboId")
                        .HasColumnType("text");

                    b.Property<string>("CreateByAdmin")
                        .HasColumnType("text");

                    b.Property<string>("CreateByUser")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<DateTime>>("EndDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("ComboId");

                    b.HasIndex("CreateByAdmin");

                    b.HasIndex("CreateByUser");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.ProductCombo.ProductComboEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("ComboId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ComboId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductComboEntity");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.User.UserEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.CombOut.ComboOutEntity", b =>
                {
                    b.HasOne("AlmacenApi.Domain.Entities.Admin.AdminEntity", "Admin")
                        .WithMany("ComboOut")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenApi.Domain.Entities.Combo.ComboEntity", "Combo")
                        .WithMany("ComboOut")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenApi.Domain.Entities.Combo.ComboEntity", "UpdateCombo")
                        .WithMany()
                        .HasForeignKey("UpdateComboid");

                    b.HasOne("AlmacenApi.Domain.Entities.User.UserEntity", "User")
                        .WithMany("ComboOut")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Combo");

                    b.Navigation("UpdateCombo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Combo.ComboEntity", b =>
                {
                    b.HasOne("AlmacenApi.Domain.Entities.Admin.AdminEntity", "Admin")
                        .WithMany("Combos")
                        .HasForeignKey("AdminId");

                    b.HasOne("AlmacenApi.Domain.Entities.User.UserEntity", "User")
                        .WithMany("Combos")
                        .HasForeignKey("UserId");

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Out.ProductOut.ProductOutEntity", b =>
                {
                    b.HasOne("AlmacenApi.Domain.Entities.Admin.AdminEntity", "Admin")
                        .WithMany("ProductOut")
                        .HasForeignKey("AdminId");

                    b.HasOne("AlmacenApi.Domain.Entities.Product.ProductEntity", "Product")
                        .WithMany("ProductOut")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenApi.Domain.Entities.User.UserEntity", "User")
                        .WithMany("ProductOut")
                        .HasForeignKey("UserId");

                    b.Navigation("Admin");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.HasOne("AlmacenApi.Domain.Entities.Combo.ComboEntity", "Combo")
                        .WithMany("Products")
                        .HasForeignKey("ComboId");

                    b.HasOne("AlmacenApi.Domain.Entities.Admin.AdminEntity", "adminEntity")
                        .WithMany("Products")
                        .HasForeignKey("CreateByAdmin");

                    b.HasOne("AlmacenApi.Domain.Entities.User.UserEntity", "userEntity")
                        .WithMany("Products")
                        .HasForeignKey("CreateByUser");

                    b.Navigation("Combo");

                    b.Navigation("adminEntity");

                    b.Navigation("userEntity");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.ProductCombo.ProductComboEntity", b =>
                {
                    b.HasOne("AlmacenApi.Domain.Entities.Combo.ComboEntity", "comboEntity")
                        .WithMany("ProductComboEntities")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenApi.Domain.Entities.Product.ProductEntity", "ProductEntity")
                        .WithMany("ProductCombos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductEntity");

                    b.Navigation("comboEntity");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Admin.AdminEntity", b =>
                {
                    b.Navigation("ComboOut");

                    b.Navigation("Combos");

                    b.Navigation("ProductOut");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Combo.ComboEntity", b =>
                {
                    b.Navigation("ComboOut");

                    b.Navigation("ProductComboEntities");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.Navigation("ProductCombos");

                    b.Navigation("ProductOut");
                });

            modelBuilder.Entity("AlmacenApi.Domain.Entities.User.UserEntity", b =>
                {
                    b.Navigation("ComboOut");

                    b.Navigation("Combos");

                    b.Navigation("ProductOut");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
